# Generated by Django 3.2.6 on 2021-09-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=30, verbose_name='キーワード')),
            ],
            options={
                'db_table': 'KeywordModel',
            },
        ),
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='ユーザーID')),
            ],
            options={
                'db_table': 'PersonModel',
            },
        ),
    ]
