# Generated by Django 3.2.6 on 2021-09-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordmodel',
            name='since',
            field=models.CharField(default='', max_length=10, verbose_name='いつから'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keywordmodel',
            name='until',
            field=models.CharField(default='', max_length=10, verbose_name='いつまで'),
            preserve_default=False,
        ),
    ]
